### ISSUE TITLE
Bug with clicking on data within the context

### ISSUE THREAD

**Issue by vincet3** [ianwalter/ng-context-menu#23]
was using this as a popup menu, worked great other than it kept closing the context before I could do anything

I updated the if statement in the click event with this, works for my case:

            if (
                !$scope.disabled() &&
                opened &&
                event.target !== ContextMenuService.menuElement &&
                !(
                    event.target === ContextMenuService.element &&
                    event.button === 2
                )
            ) {

**Comment by ianwalter** [comment]
Closing this and creating a new issue.
