### ISSUE TITLE
Open the menu programmatically at specific position

### ISSUE THREAD

**Issue by DumboJet** [ianwalter/ng-context-menu#36]
Hi there.

Thanks for the nice library.

Can I somehow open the menu programmatically at specific position?
I will try to do it myself, but I think it would be nice if you allowed this in a built-in manner, so that I don't have to branch your lib.

Thanks! :)

**Comment by onexdata** [comment]
DumboJet; it would be nice if you fork and/or post your solution... you are teasing everyone.

**Comment by DumboJet** [comment]
Sorry for that.
My requirement was to make a button open a context menu that was used elsewhere.
The main idea was to trigger the 'contextmenu' programmatically when the user left clicked on a button that was set-up to open the context menu on right click:

        $scope.OpenDropDown = function () {
            setTimeout(function () {
                var el = $('#ddmBtn');
                var rect = el[0].getBoundingClientRect();
                var menu = $('#menu-document');

                el.triggerHandler('contextmenu');

                menu.css('top', rect.bottom + 'px');
                var ddmWidth = $('#ddm').width();
                var rightLimit = rect.left + el[0].offsetWidth;
                var left = rightLimit - ddmWidth;
                menu.css('left', left + 'px');
            }, 200);
        };

ddm = Drop down menu.
ddmBtn = Button that open the drop down.
Here is some HTML that may help you locate "menu-document" and "ddm":

    <div class="dropdown position-fixed open" id="menu-document">
            <ul class="dropdown-menu multi-level" role="menu" id="ddm">

I hope this helps. :)

**Comment by ianwalter** [comment]
I'm sure you have good reason for this functionality but it doesn't fit within the concept of a context menu. It would best be implemented in a separate directive/library.
