### ISSUE TITLE
scrollWidth error on right-click

### ISSUE THREAD

**Issue by grosch** [ianwalter/ng-context-menu#48]
I added your module and then stuck this HTML in for the context menu:

```html
<div class="dropdown position-fixed" id="menu-{{ $index }}">
  <ul class="dropdown-menu" role="menu">
    <li>
      <a class="pointer" role="menuitem" tabindex="1">
        This is panel {{ $index + 1 }}
      </a>
    <li>
  </ul>
</div>
```

Then, on my table's tr I added the two attributes I think I need:

```html
<tr ng-repeat="..." context-menu data-target="menu-{{ $index }}">
```

When I right-click in my table, Chrome is showing me an error:

```
angular.js:11413 TypeError: Cannot read property 'scrollWidth' of undefined
    at open (ng-context-menu.js:40)
    at ng-context-menu.js:89
    at k.$get.k.$eval (angular.js:14204)
    at k.$get.k.$apply (angular.js:14302)
    at HTMLTableRowElement.<anonymous> (ng-context-menu.js:88)
    at HTMLTableRowElement.c (angular.js:2990)
angular.js:11413(anonymous function)
angular.js:8473$get
angular.js:14304$get.k.$apply
ng-context-menu.js:88(anonymous function)
angular.js:2990c
.
```

What did I forget to do?

**Comment by ianwalter** [comment]
Where did you put the menu? Is it inside of the table row?

**Comment by grosch** [comment]
You mean the div I showed first?  I tried it both inside the tr and at the
same level as the table.

**Comment by ianwalter** [comment]
You get $index from the ng-repeat so the menu has to be inside of it if you're going to use $index. That error means it cannot find the menu element. The values inside of data-target="" and id="" must match. Closing because this is an implementation issue not and issue with the plugin.
