### ISSUE TITLE
Positioning with UI Grid is off?

### ISSUE THREAD

**Issue by mikehuebner** [ianwalter/ng-context-menu#52]
I'm trying to use the context menu (which is amazing by the way, thank you for this!) on the UI Grid by the Angular UI team and it seems offset by quite a lot! I don't know why exactly but has this issue been brought up before by anyone? If so what can I do to solve it and prevent it for the future, thanks!

**Comment by ro0sterjam** [comment]
Having the same issue.

**Comment by ianwalter** [comment]
Maybe someone can set up a plunkr or jsfiddle so I can help you troubleshoot.

**Comment by trumaj** [comment]
I'm having the same issue. Context menu pops up half a screen away from current mouse pointer position.

@ro0sterjam @mikehuebner Did you guys manage to get around it?

**Comment by trumaj** [comment]
On investigation, the context menu was being positioned relative to the current viewport (position: fixed) which was causing the menu to appear greatly offset from the desired position.

I got around the issue by removing the css class "position-fixed" from the menu definition div, and replacing it with an explicit style="position: absolute;".

Did the trick and didn't require any changes to the library.
