### ISSUE TITLE
Change ng-content-menu from right click to left click

### ISSUE THREAD

**Issue by liadlivnat** [ianwalter/ng-context-menu#55]
I'm using ng-context-menu An AngularJS directive to display a context menu when a right-click event is triggered.

I wish to change the menu behavior so it will open on left click instead of right click.

Does anyone knows what should i change?

**Comment by lh8725473** [comment]
I have the same question

**Comment by ianwalter** [comment]
Take a look at my plugin, [ng-dropdown](https://github.com/ianwalter/ng-dropdown). On the demo it's styled as a custom select but you can style it anyway you want. It's made for left-clicking and opening a menu.
