### ISSUE TITLE
Menu offset in Modal window

### ISSUE THREAD

**Issue by jasontruland** [ianwalter/ng-context-menu#66]
The context menu works well on my main page but when I use it on a modal dialog the offset is way off. Has anyone seen this?

**Comment by z0ran8** [comment]
Happened to me too. Do you have a solution @jasontruland ?

**Comment by jasontruland** [comment]
I have not found one yet...

**Comment by ianwalter** [comment]
Yes, this happens when you include the menu markup within the modal markup. The modal styles then mess up the positioning of the menu. Put the menu markup outside of the modal markup. You may run into scope issues, but they are actually easier to work around.

**Comment by jasontruland** [comment]
Yes, that seems to place it in the correct position but it also places it behind the modal dialog..,. So I can't see it.

**Comment by ianwalter** [comment]
You can simply use the z-index CSS property to manipulate that.
