### ISSUE TITLE
npm version problem

### ISSUE THREAD

**Issue by antoinegomez** [ianwalter/ng-context-menu#68]
Hello,

Tried to install the module via npm to use it with browserify.
The current version is 1.0.2 here but on npm it is 0.1.1 ... and refer to another repo. Aich.
On the other repo we can see in package.json that the name of the plugin is different. Well...

I am forking this and publishing in a private repo but if I am not alone using browserify it could be nice to sort things. Maybe an email to the current owner ng-context-menu on npm would be enough to get it back.

**Comment by ianwalter** [comment]
Will publish in a few.

**Comment by ianwalter** [comment]
Whoops, misunderstood the issue and someone else has taken the name on npm. I'm not really inclined to publish to npm anyway. You should be able to still install from bower and use the package with browserify. Closing.
